### 

POST http://localhost:8080/events HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzczNzc3MDM2LCJ1c2VySWQiOjB9.xe4uq1LDdyzc--4sgeNtuNNGYyW9ab5fWaUt2x_1hlA

{
  "dateTime": "2025-01-01T15:30:00.000Z",
  "description": "A test event",
  "location": "A test location",
  "name": "Test event"
}
